server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Roshni-Romeshika/spring-cloud-config-store
          #uri: https://github.com/krish/spring-cloud-config
          search-paths:
           - '*service'



