server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Roshni-Romeshika/spring-cloud-config-store
          search-paths:
           - '*service'
           
           
           #uri: https://github.com/Roshni-Romeshika/spring-cloud-config-storehttps://github.com/krish/spring-cloud-config



